import { test, expect } from "@playwright/test";
import { existsSync, mkdirSync, rmSync, writeFileSync, readFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

/**
 * Full lifecycle E2E test with mocked AI responses.
 *
 * Runs against a clean .planning/ folder in a temp directory.
 * The server runs with DCL_MOCK_AI pointing to fixture responses,
 * so all AI calls return deterministic data while the real server
 * code (parsing, file writing, SSE, graph building) runs normally.
 *
 * Flow: empty project → onboarding → declarations → derive milestones
 *       → plan actions → execute → verify
 */

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = resolve(__dirname, "../..");
const TMP = resolve(PROJECT_ROOT, "test-results/lifecycle-project");

test.describe.configure({ mode: "serial" });

test.beforeAll(() => {
  // Create a clean project directory
  if (existsSync(TMP)) rmSync(TMP, { recursive: true });
  mkdirSync(resolve(TMP, ".planning"), { recursive: true });
  writeFileSync(
    resolve(TMP, ".planning", "FUTURE.md"),
    "# Future: Project\n",
    "utf-8"
  );
  writeFileSync(
    resolve(TMP, ".planning", "MILESTONES.md"),
    [
      "# Milestones: Project",
      "",
      "## Milestones",
      "",
      "| ID | Title | Status | Realizes | Plan | Review |",
      "|----|-------|--------|----------|------|--------|",
      "",
    ].join("\n"),
    "utf-8"
  );
  writeFileSync(
    resolve(TMP, ".planning", "config.json"),
    '{\n  "commit_docs": true\n}\n',
    "utf-8"
  );
});

test.afterAll(() => {
  // Clean up — comment this out to inspect state after test
  // if (existsSync(TMP)) rmSync(TMP, { recursive: true });
});

// ── Step 1: Empty project shows onboarding ──

test("empty project shows onboarding screen", async ({ page }) => {
  await page.goto("/");
  await page.waitForLoadState("domcontentloaded");

  // Should show the onboarding flow
  await expect(
    page.getByText("What is true when this project succeeds?")
  ).toBeVisible({ timeout: 10_000 });

  // Vision textarea should be present
  await expect(
    page.getByPlaceholder("When this project succeeds...")
  ).toBeVisible();
});

// ── Step 2: Enter vision and get AI questions ──

test("vision → AI questions flow works", async ({ page }) => {
  await page.goto("/");
  await page.waitForLoadState("domcontentloaded");

  // Enter vision text
  const textarea = page.getByPlaceholder("When this project succeeds...");
  await textarea.fill(
    "A CLI tool that converts markdown files to professionally styled PDFs with custom themes, fast batch processing, and first-class GitHub-Flavored Markdown support."
  );

  // Click Next
  await page.getByRole("button", { name: /next/i }).click();

  // Should show questions generated by mocked AI
  await expect(
    page.getByText("A few clarifying questions")
  ).toBeVisible({ timeout: 15_000 });

  // Should have the questions from our fixture
  await expect(
    page.getByText("What types of markdown files")
  ).toBeVisible();
});

// ── Step 3: Answer questions and generate declarations ──

test("questions → declarations generation works", async ({ page }) => {
  await page.goto("/");
  await page.waitForLoadState("domcontentloaded");

  // Re-enter vision (state is not persisted across page loads)
  const textarea = page.getByPlaceholder("When this project succeeds...");
  await textarea.fill(
    "A CLI tool that converts markdown files to professionally styled PDFs with custom themes, fast batch processing, and first-class GitHub-Flavored Markdown support."
  );
  await page.getByRole("button", { name: /next/i }).click();

  // Wait for questions
  await expect(
    page.getByText("A few clarifying questions")
  ).toBeVisible({ timeout: 15_000 });

  // Select some options (click the suggestion chips)
  const gfmOption = page.getByRole("button", { name: "GitHub-Flavored Markdown" });
  if (await gfmOption.isVisible()) {
    await gfmOption.click();
  }

  // Click Generate Declarations
  await page.getByRole("button", { name: /generate declarations/i }).click();

  // Wait for declarations to appear — the UI should transition to lifecycle view
  // The mocked AI returns 3 declarations, which get created via POST /api/declarations
  await expect(page.getByText("D-01").first()).toBeVisible({ timeout: 15_000 });
  await expect(page.getByText("Markdown-to-PDF").first()).toBeVisible();
});

// ── Step 4: Verify declarations exist in graph ──

test("declarations are in the graph API", async ({ request }) => {
  const res = await request.get("/api/graph");
  expect(res.ok()).toBe(true);

  const graph = await res.json();
  expect(graph.declarations.length).toBe(3);
  expect(graph.declarations[0].id).toBe("D-01");
  expect(graph.declarations[0].title).toContain("Markdown-to-PDF");
  expect(graph.projectName).toBe("MD2PDF Pro");

  // Verify files were written to the tmp dir
  const future = readFileSync(resolve(TMP, ".planning", "FUTURE.md"), "utf-8");
  expect(future).toContain("D-01");
  expect(future).toContain("D-02");
  expect(future).toContain("D-03");
});

// ── Step 5: Approve declarations ──

test("approve all declarations", async ({ request }) => {
  const res = await request.post("/api/approve-batch", {
    data: { ids: ["D-01", "D-02", "D-03"] },
  });
  expect(res.ok()).toBe(true);
  const body = await res.json();
  expect(body.approved).toEqual(["D-01", "D-02", "D-03"]);
});

// ── Step 6: Derive milestones via mocked AI ──

test("derive milestones for D-01", async ({ request }) => {
  const res = await request.post("/api/agents/derive", {
    data: { declarationId: "D-01" },
  });
  expect(res.ok()).toBe(true);
  const agent = await res.json();
  expect(agent.type).toBe("derivation");
  expect(agent.status).toBe("running");

  // Wait for the mocked AI to complete (100ms delay + file write)
  await new Promise((r) => setTimeout(r, 2000));

  // Check agent completed
  const agentRes = await request.get(`/api/agents/${agent.id}`);
  const updated = await agentRes.json();
  expect(updated.status).toBe("completed");

  // Verify milestones were written
  const graph = await (await request.get("/api/graph")).json();
  expect(graph.milestones.length).toBeGreaterThanOrEqual(2);
  expect(graph.milestones.some((m: any) => m.id === "M-01")).toBe(true);
});

// ── Step 7: Dashboard shows milestones ──

test("dashboard shows derived milestones", async ({ page }) => {
  await page.goto("/");
  await page.waitForLoadState("domcontentloaded");

  // Click on D-01 to see its milestones in the detail panel
  await page.getByText("D-01").first().click({ timeout: 5_000 });

  // Milestones appear as a numbered list in the detail panel
  // Look for the milestone title text (rendered as list items, not "M-01")
  await expect(page.getByText("GFM parser").first()).toBeVisible({ timeout: 10_000 });
  await expect(page.getByText("MILESTONES").first()).toBeVisible();
});

// ── Step 8: Approve milestones and plan actions ──

test("approve milestones and plan actions for M-01", async ({ request }) => {
  // Approve M-01
  const approveRes = await request.post("/api/approve-batch", {
    data: { ids: ["M-01"] },
  });
  expect(approveRes.ok()).toBe(true);

  // Plan actions
  const planRes = await request.post("/api/agents/plan-actions", {
    data: { milestoneId: "M-01" },
  });
  expect(planRes.ok()).toBe(true);
  const agent = await planRes.json();

  // Wait for mocked AI to complete
  await new Promise((r) => setTimeout(r, 2000));

  const updated = await (await request.get(`/api/agents/${agent.id}`)).json();
  expect(updated.status).toBe("completed");

  // Verify actions in graph
  const graph = await (await request.get("/api/graph")).json();
  expect(graph.actions.length).toBeGreaterThanOrEqual(2);
  expect(graph.actions.some((a: any) => a.id === "A-01")).toBe(true);

  // Verify PLAN.md was written
  const planDir = resolve(TMP, ".planning", "milestones");
  expect(existsSync(planDir)).toBe(true);
});

// ── Step 9: Dashboard shows actions ──

test("dashboard shows planned actions", async ({ page }) => {
  await page.goto("/");
  await page.waitForLoadState("domcontentloaded");

  // Drill into D-01 → milestones level
  await page.getByText("D-01").first().click({ timeout: 5_000 });
  await page.keyboard.press("ArrowRight");
  await page.waitForTimeout(500);

  // Click on GFM parser milestone
  await page.getByText("GFM parser").first().click({ timeout: 5_000 });

  // Actions should show in detail or after further drill
  await page.keyboard.press("ArrowRight");
  await page.waitForTimeout(500);

  // Verify actions are accessible via API at minimum
  const graph = await (await page.request.get("/api/graph")).json();
  expect(graph.actions.length).toBeGreaterThanOrEqual(2);
});

// ── Step 10: Execute an action ──

test("execute action A-01", async ({ request }) => {
  const res = await request.post("/api/agents/execute", {
    data: { actionId: "A-01" },
  });
  expect(res.ok()).toBe(true);
  const agent = await res.json();
  expect(agent.type).toBe("execution");

  // Wait for mocked AI
  await new Promise((r) => setTimeout(r, 2000));

  const updated = await (await request.get(`/api/agents/${agent.id}`)).json();
  expect(updated.status).toBe("completed");
  expect(updated.output).toContain("A-01");
});

// ── Step 11: Verify milestone M-01 ──

test("verify milestone M-01", async ({ request }) => {
  const res = await request.post("/api/agents/verify", {
    data: { milestoneId: "M-01" },
  });
  expect(res.ok()).toBe(true);
  const agent = await res.json();
  expect(agent.type).toBe("verification");

  // Wait for mocked AI
  await new Promise((r) => setTimeout(r, 2000));

  const updated = await (await request.get(`/api/agents/${agent.id}`)).json();
  expect(updated.status).toBe("completed");
  expect(updated.output).toContain("VERIFIED");
});

// ── Step 12: Final graph state is consistent ──

test("final graph state is consistent", async ({ request }) => {
  const res = await request.get("/api/graph");
  const graph = await res.json();

  // 3 declarations from onboarding
  expect(graph.declarations.length).toBe(3);

  // At least 2 milestones from derive
  expect(graph.milestones.length).toBeGreaterThanOrEqual(2);

  // At least 2 actions from plan
  expect(graph.actions.length).toBeGreaterThanOrEqual(2);

  // Stats match
  expect(graph.stats.declarations).toBe(graph.declarations.length);
  expect(graph.stats.milestones).toBe(graph.milestones.length);
  expect(graph.stats.actions).toBe(graph.actions.length);

  // No validation errors
  expect(graph.validation.errors).toEqual([]);

  // Project was renamed during onboarding
  expect(graph.projectName).toBe("MD2PDF Pro");
});

// ── Step 13: Agent history shows all runs ──

test("agent history shows complete run log", async ({ request }) => {
  const res = await request.get("/api/agents");
  const agents = await res.json();

  // Should have at least: derive, plan-actions, execute, verify
  expect(agents.length).toBeGreaterThanOrEqual(4);

  const types = agents.map((a: any) => a.type);
  expect(types).toContain("derivation");
  expect(types).toContain("execution");
  expect(types).toContain("verification");

  // All should be completed
  const statuses = agents.map((a: any) => a.status);
  expect(statuses.every((s: string) => s === "completed")).toBe(true);
});

// ── Step 14: Files on disk match expectations ──

test("planning files on disk are correct", async () => {
  // FUTURE.md has declarations
  const future = readFileSync(resolve(TMP, ".planning", "FUTURE.md"), "utf-8");
  expect(future).toContain("# Future: MD2PDF Pro");
  expect(future).toContain("## D-01:");
  expect(future).toContain("## D-02:");
  expect(future).toContain("## D-03:");

  // MILESTONES.md has milestones
  const milestones = readFileSync(
    resolve(TMP, ".planning", "MILESTONES.md"),
    "utf-8"
  );
  expect(milestones).toContain("M-01");
  expect(milestones).toContain("GFM parser");

  // PLAN.md exists for M-01
  const planDir = resolve(TMP, ".planning", "milestones");
  expect(existsSync(planDir)).toBe(true);
});
